Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@orkandasamy 
orkandasamy
/
devops-directive-terraform-course
Public
forked from sidpalas/devops-directive-terraform-course
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
devops-directive-terraform-course/.github/workflows/terraform.yml
@sidpalas
sidpalas disable staging deploy
Latest commit 7592206 on Feb 13
 History
 1 contributor
112 lines (92 sloc)  3.54 KB
   
name: "Terraform"

on:
  # Uncomment to enable staging deploy from main
  # push:
  #   branches:
  #     - main
  release:
    types: [published]
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

    
